// <auto-generated />
using System;
using Rebet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Rebet.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124205532_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rebet.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentableId")
                        .HasColumnType("uuid");

                    b.Property<int>("CommentableType")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CommentableType", "CommentableId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.EventMarketData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MarketsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SnapshotEpoch")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SportEventId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarketsJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MarketsJson"), "gin");

                    b.HasIndex("SportEventId")
                        .IsUnique();

                    b.ToTable("event_market_data", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.EventResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalScore")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HalfTimeScore")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MarketResultsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SportEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Winner")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("SettledAt")
                        .IsDescending();

                    b.HasIndex("SportEventId")
                        .IsUnique();

                    b.ToTable("event_results", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Expert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<decimal>("CommissionRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.1000m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DownvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Specialization")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Status")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UpvoteCount")
                        .IsDescending()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("experts", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.ExpertStatistics", b =>
                {
                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveSubscribers")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<decimal>("Last30DaysWinRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Last7DaysWinRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Last90DaysWinRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LongestWinStreak")
                        .HasColumnType("integer");

                    b.Property<int>("LostPositions")
                        .HasColumnType("integer");

                    b.Property<int>("PendingPositions")
                        .HasColumnType("integer");

                    b.Property<decimal>("ROI")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("TotalCommissionEarned")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalPositions")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalProfit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalSubscribers")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VoidPositions")
                        .HasColumnType("integer");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("WonPositions")
                        .HasColumnType("integer");

                    b.HasKey("ExpertId");

                    b.HasIndex("ROI")
                        .IsDescending();

                    b.HasIndex("WinRate")
                        .IsDescending();

                    b.ToTable("expert_statistics", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExpertStatistics_Last30DaysWinRate_Range", "\"Last30DaysWinRate\" >= 0 AND \"Last30DaysWinRate\" <= 100");

                            t.HasCheckConstraint("CK_ExpertStatistics_Last7DaysWinRate_Range", "\"Last7DaysWinRate\" >= 0 AND \"Last7DaysWinRate\" <= 100");

                            t.HasCheckConstraint("CK_ExpertStatistics_Last90DaysWinRate_Range", "\"Last90DaysWinRate\" >= 0 AND \"Last90DaysWinRate\" <= 100");

                            t.HasCheckConstraint("CK_ExpertStatistics_WinRate_Range", "\"WinRate\" >= 0 AND \"WinRate\" <= 100");
                        });
                });

            modelBuilder.Entity("Rebet.Domain.Entities.NewsfeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ExpertId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("ExpertId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("PositionId");

                    b.HasIndex("TicketId");

                    b.HasIndex("Type")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("newsfeed_items", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead")
                        .HasFilter("\"IsRead\" = false");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Analysis")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("CreatorType")
                        .HasColumnType("integer");

                    b.Property<int>("DownvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Odds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PredictionPercentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SportEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("VoterCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatorId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("SportEventId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Status")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UpvoteCount")
                        .IsDescending()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatorType", "Status")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("positions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Position_Odds_Positive", "\"Odds\" > 0");
                        });
                });

            modelBuilder.Entity("Rebet.Domain.Entities.SportEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AwayTeamLogo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("AwayWinOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DrawOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasActiveTickets")
                        .HasColumnType("boolean");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HomeTeamLogo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("HomeWinOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Over25Odds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("StartTimeEpoch")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Under25Odds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalEventId")
                        .IsUnique();

                    b.HasIndex("StartTimeEpoch")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Sport", "Status")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Status", "StartTimeEpoch")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("sport_events", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("SubscribedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ExpertId")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("DownvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("FollowerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PotentialReturn")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettlementNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Stake")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("ExpertId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Status")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UpvoteCount")
                        .IsDescending()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ticket_Odds_Positive", "\"TotalOdds\" > 0");

                            t.HasCheckConstraint("CK_Ticket_PotentialReturn_Valid", "\"PotentialReturn\" >= \"Stake\"");

                            t.HasCheckConstraint("CK_Ticket_Stake_Positive", "\"Stake\" > 0");
                        });
                });

            modelBuilder.Entity("Rebet.Domain.Entities.TicketEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Analysis")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("EventStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Handicap")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("League")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Odds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<string>("ResultNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SportEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SportEventId");

                    b.HasIndex("Status");

                    b.HasIndex("TicketId");

                    b.ToTable("ticket_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketEntry_Odds_Positive", "\"Odds\" > 0");
                        });
                });

            modelBuilder.Entity("Rebet.Domain.Entities.TicketFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketFollows");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("RelatedExpertId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTicketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("RelatedExpertId");

                    b.HasIndex("RelatedTicketId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionReference")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("WalletId");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_Transaction_Balance_Consistent", "\"BalanceAfter\" = \"BalanceBefore\" + \"Amount\" * CASE WHEN \"Type\" IN (1, 3, 4) THEN 1 WHEN \"Type\" = 2 THEN -1 ELSE 0 END");
                        });
                });

            modelBuilder.Entity("Rebet.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Role")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceivePushNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId");

                    b.HasIndex("DisplayName");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoteableId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteableType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteableType", "VoteableId");

                    b.HasIndex("UserId", "VoteableType", "VoteableId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("PendingBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Wallet_Balance_NonNegative", "\"Balance\" >= 0");

                            t.HasCheckConstraint("CK_Wallet_PendingBalance_NonNegative", "\"PendingBalance\" >= 0");
                        });
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rebet.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.EventMarketData", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.SportEvent", "SportEvent")
                        .WithOne("MarketData")
                        .HasForeignKey("Rebet.Domain.Entities.EventMarketData", "SportEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportEvent");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.EventResult", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.SportEvent", "SportEvent")
                        .WithOne("Result")
                        .HasForeignKey("Rebet.Domain.Entities.EventResult", "SportEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportEvent");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Expert", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.User", "User")
                        .WithOne("Expert")
                        .HasForeignKey("Rebet.Domain.Entities.Expert", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.ExpertStatistics", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.Expert", "Expert")
                        .WithOne("Statistics")
                        .HasForeignKey("Rebet.Domain.Entities.ExpertStatistics", "ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.NewsfeedItem", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rebet.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rebet.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Expert");

                    b.Navigation("Position");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Position", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.User", "Creator")
                        .WithMany("Positions")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rebet.Domain.Entities.SportEvent", "SportEvent")
                        .WithMany("Positions")
                        .HasForeignKey("SportEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("SportEvent");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.Expert", "Expert")
                        .WithMany("Subscribers")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rebet.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.Expert", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rebet.Domain.Entities.TicketEntry", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.SportEvent", "SportEvent")
                        .WithMany("TicketEntries")
                        .HasForeignKey("SportEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rebet.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Entries")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportEvent");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.TicketFollow", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rebet.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.Expert", "RelatedExpert")
                        .WithMany()
                        .HasForeignKey("RelatedExpertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rebet.Domain.Entities.Ticket", "RelatedTicket")
                        .WithMany()
                        .HasForeignKey("RelatedTicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rebet.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedExpert");

                    b.Navigation("RelatedTicket");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Rebet.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Vote", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Rebet.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Rebet.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Expert", b =>
                {
                    b.Navigation("Statistics");

                    b.Navigation("Subscribers");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.SportEvent", b =>
                {
                    b.Navigation("MarketData");

                    b.Navigation("Positions");

                    b.Navigation("Result");

                    b.Navigation("TicketEntries");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Rebet.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Expert");

                    b.Navigation("Positions");

                    b.Navigation("Profile");

                    b.Navigation("Subscriptions");

                    b.Navigation("Votes");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
